Repository SGMRT/sgmrt-server, pull requests merged in 2025-07, with the labels that each got.

#14 [SGMR-267] 러닝 공개유무 수정 API 개발 및 테스트 환경 구축
  src/main/java/soma/ghostrunner/domain/course/dto/CourseMapper.java
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/api/dto/RunningApiMapper.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningCommandService.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/GhostRunDetailInfo.java
  src/main/java/soma/ghostrunner/domain/running/domain/Running.java
  src/main/java/soma/ghostrunner/domain/running/domain/support/CourseCoordinateConverter.java
  src/main/java/soma/ghostrunner/domain/running/domain/support/TelemetryCalculator.java
  src/main/java/soma/ghostrunner/domain/running/exception/InvalidGhostRunningException.java
  src/main/java/soma/ghostrunner/domain/running/exception/InvalidRunningException.java
  src/main/java/soma/ghostrunner/global/common/error/ErrorCode.java
  src/main/java/soma/ghostrunner/global/common/error/exception/InvalidValueException.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/soma/ghostrunner/ApiTestSupport.java
  src/test/java/soma/ghostrunner/IntegrationTestSupport.java
  src/test/java/soma/ghostrunner/domain/running/api/RunningApiTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningCommandServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/running/domain/RunningTest.java
  src/test/java/soma/ghostrunner/domain/running/domain/TelemetryCalculatorTest.java
Labels: enhancement, refactor

#17 [SGMR-284] 특정 회원의 코스 랭킹 순위 조회 API 응답에 러닝기록 데이터 추가
  src/main/java/soma/ghostrunner/domain/course/api/CourseApi.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseRankingResponse.java
  src/main/java/soma/ghostrunner/domain/running/api/dto/RunningApiMapper.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/dao/RunningRepository.java
Labels: fix

#20 [SGMR-198] 코스 조회 API에서 QueryParameter로 검색 조건 필터링 가능하도록 변경
  src/main/java/soma/ghostrunner/domain/course/api/CourseApi.java
  src/main/java/soma/ghostrunner/domain/course/application/CourseService.java
  src/main/java/soma/ghostrunner/domain/course/dao/CustomCourseRepository.java
  src/main/java/soma/ghostrunner/domain/course/dao/CustomCourseRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/course/domain/Course.java
  src/main/java/soma/ghostrunner/domain/course/dto/request/CoursePatchRequest.java
  src/main/java/soma/ghostrunner/domain/course/enums/AvailableGhostSortField.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/global/common/error/GlobalExceptionAdvice.java
Labels: enhancement

#24 [SGMR-329] Course 도메인 Facade 패턴 도입 및 코스 기반 시계열 조회 API 구현
  src/main/java/soma/ghostrunner/domain/course/api/CourseApi.java
  src/main/java/soma/ghostrunner/domain/course/application/CourseFacade.java
  src/main/java/soma/ghostrunner/domain/course/dto/CourseMapper.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseCoordinatesResponse.java
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/api/dto/RunningApiMapper.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepository.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
Labels: enhancement, refactor

#27 [SGMR-268] 러닝 기록 조회 API 개발
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/CourseInfo.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/RunInfo.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/RunRecordInfo.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepository.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/dao/RunningRepository.java
  src/main/java/soma/ghostrunner/global/common/error/ErrorCode.java
  src/main/java/soma/ghostrunner/global/common/error/GlobalExceptionAdvice.java
  src/main/java/soma/ghostrunner/global/common/log/HttpLogMessage.java
  src/main/java/soma/ghostrunner/global/common/validator/enums/EnumValid.java
  src/main/resources/logback-spring.xml
  src/test/java/soma/ghostrunner/domain/running/api/RunningApiTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
  src/test/java/soma/ghostrunner/learning/JpaModifyingTest.java
Labels: enhancement

#35 [SGMR-364] 리프레쉬 토큰을 활용한 로그아웃 및 토큰 재발급 기능 구현
  src/main/java/soma/ghostrunner/domain/auth/api/AuthApi.java
  src/main/java/soma/ghostrunner/domain/auth/application/AuthService.java
  src/main/java/soma/ghostrunner/domain/auth/application/RefreshTokenService.java
  src/main/java/soma/ghostrunner/domain/auth/exception/TokenTheftException.java
  src/main/java/soma/ghostrunner/domain/course/application/CourseFacade.java
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepository.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/dao/RunningRepository.java
  src/main/java/soma/ghostrunner/global/config/RedisConfig.java
  src/main/java/soma/ghostrunner/global/error/ErrorCode.java
  src/main/java/soma/ghostrunner/global/security/jwt/JwtAuthFilter.java
  src/main/java/soma/ghostrunner/global/security/jwt/factory/JwtTokenFactory.java
  src/main/java/soma/ghostrunner/global/security/jwt/support/JwtProvider.java
  src/main/resources/application-dev.yml
  src/test/java/soma/ghostrunner/domain/auth/api/AuthApiTest.java
  src/test/java/soma/ghostrunner/domain/auth/application/AuthServiceTest.java
  src/test/java/soma/ghostrunner/domain/auth/application/RefreshTokenServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
  src/test/java/soma/ghostrunner/global/security/jwt/factory/JwtTokenFactoryTest.java
  src/test/java/soma/ghostrunner/global/security/jwt/support/JwtProviderTest.java
Labels: enhancement

#36 [SGMR-322] 회원 정보 수정 API & 약관 동의 여부 수정 API 개발
  src/main/java/soma/ghostrunner/domain/auth/api/dto/request/SignUpRequest.java
  src/main/java/soma/ghostrunner/domain/auth/application/AuthService.java
  src/main/java/soma/ghostrunner/domain/course/dao/CustomCourseRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/course/domain/Course.java
  src/main/java/soma/ghostrunner/domain/course/dto/CourseMapper.java
  src/main/java/soma/ghostrunner/domain/member/api/MemberApi.java
  src/main/java/soma/ghostrunner/domain/member/api/MemberController.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/TermsAgreementDto.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/MemberUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/ProfileImageUploadRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/response/MemberResponse.java
  src/main/java/soma/ghostrunner/domain/member/application/MemberService.java
  src/main/java/soma/ghostrunner/domain/member/application/dto/MemberMapper.java
  src/main/java/soma/ghostrunner/domain/member/dao/MemberRepository.java
  src/main/java/soma/ghostrunner/domain/member/dao/TermsAgreementRepository.java
  src/main/java/soma/ghostrunner/domain/member/domain/Member.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberAuthInfo.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberBioInfo.java
  src/main/java/soma/ghostrunner/domain/member/domain/TermsAgreement.java
  src/main/java/soma/ghostrunner/domain/member/exception/InvalidMemberException.java
  src/main/java/soma/ghostrunner/domain/member/exception/MemberNotFoundException.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningCommandService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/domain/Running.java
  src/main/java/soma/ghostrunner/global/config/SwaggerConfig.java
  src/main/java/soma/ghostrunner/global/error/ErrorCode.java
  src/test/java/soma/ghostrunner/domain/auth/api/AuthApiTest.java
  src/test/java/soma/ghostrunner/domain/auth/application/AuthServiceTest.java
  src/test/java/soma/ghostrunner/domain/member/MemberRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/member/dao/MemberAuthInfoRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningCommandServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/running/domain/RunningTest.java
  src/test/java/soma/ghostrunner/learning/JpaModifyingTest.java
Labels: enhancement

#42 [SGMR-426] 회원 환경설정 저장 API 구현
  src/main/java/soma/ghostrunner/domain/member/api/MemberApi.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/MemberSettingsUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/response/MemberResponse.java
  src/main/java/soma/ghostrunner/domain/member/application/MemberService.java
  src/main/java/soma/ghostrunner/domain/member/application/dto/MemberMapper.java
  src/main/java/soma/ghostrunner/domain/member/dao/MemberRepository.java
  src/main/java/soma/ghostrunner/domain/member/dao/MemberSettingsRepository.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberSettings.java
  src/main/java/soma/ghostrunner/domain/member/exception/MemberSettingsNotFoundException.java
  src/test/java/soma/ghostrunner/domain/member/application/MemberServiceTest.java
  src/test/java/soma/ghostrunner/domain/member/domain/MemberSettingsTest.java
Labels: enhancement

#40 [SGMR-368] 회원가입 시 프로필 사진 저장을 위한 Presigned-Url 로직 설계
  src/main/java/soma/ghostrunner/clients/aws/S3PresignProvider.java
  src/main/java/soma/ghostrunner/clients/aws/presign/PresignUrlDto.java
  src/main/java/soma/ghostrunner/clients/aws/presign/PresignUrlType.java
  src/main/java/soma/ghostrunner/clients/aws/presign/S3PresignUrlClient.java
  src/main/java/soma/ghostrunner/clients/aws/upload/S3TelemetryClient.java
  src/main/java/soma/ghostrunner/domain/member/api/MemberApi.java
  src/main/java/soma/ghostrunner/domain/member/application/MemberService.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningCommandService.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/global/common/CommonApi.java
  src/main/java/soma/ghostrunner/global/config/AwsConfig.java
  src/main/java/soma/ghostrunner/global/security/jwt/JwtAuthFilter.java
  src/main/resources/application-dev.yml
  src/test/java/soma/ghostrunner/ApiTestSupport.java
  src/test/java/soma/ghostrunner/clients/aws/S3PresignUrlClientTest.java
  src/test/java/soma/ghostrunner/clients/aws/S3TelemetryClientTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningCommandServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryServiceTest.java
  src/test/java/soma/ghostrunner/global/common/CommonApiTest.java
  src/test/resources/application.yml
Labels: enhancement
