Repository SGMRT/sgmrt-server, pull requests merged in 2025-08, with the labels that each got.

#46 [SGMR-429] Grafana 구성을 위한 Prometheus 및 Actuator 의존성 추가
  build.gradle
  src/main/resources/application-dev.yml
Labels: chores

#49 [SGMR-454] 회원 수정 API 요청 필드에 profileImageUrl 추가
  src/main/java/soma/ghostrunner/clients/aws/presign/S3PresignUrlClient.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/MemberUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/member/application/MemberService.java
  src/main/java/soma/ghostrunner/domain/member/domain/Member.java
  src/test/java/soma/ghostrunner/domain/member/application/MemberServiceTest.java
Labels: update

#50 [UPDATE] 예외 발생 시 Sentry에 HTTP request body까지 전송하도록 변경
  src/main/resources/application-dev.yml
Labels: update

#52 [SGMR-496] 회원 환경설정 항목에 음성 가이드 허용 여부 추가
  src/main/java/soma/ghostrunner/domain/auth/api/AuthApi.java
  src/main/java/soma/ghostrunner/domain/auth/api/dto/request/SignUpRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/MemberApi.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/MemberSettingsUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/request/MemberUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/member/api/dto/response/MemberResponse.java
  src/main/java/soma/ghostrunner/domain/member/application/MemberService.java
  src/main/java/soma/ghostrunner/domain/member/application/dto/MemberCreationRequest.java
  src/main/java/soma/ghostrunner/domain/member/dao/MemberAuthInfoRepository.java
  src/main/java/soma/ghostrunner/domain/member/dao/MemberRepository.java
  src/main/java/soma/ghostrunner/domain/member/dao/TermsAgreementRepository.java
  src/main/java/soma/ghostrunner/domain/member/domain/Member.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberBioInfo.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberSettings.java
  src/main/java/soma/ghostrunner/domain/member/domain/TermsAgreement.java
  src/test/java/soma/ghostrunner/domain/auth/api/AuthApiTest.java
  src/test/java/soma/ghostrunner/domain/auth/application/AuthServiceTest.java
  src/test/java/soma/ghostrunner/domain/member/application/MemberServiceTest.java
Labels: update

#58 [SGMR-505] 러닝 리스트 조회 APIs 수정
  src/main/java/soma/ghostrunner/domain/course/dao/CustomCourseRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningTelemetryQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/RunningServiceMapper.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/RunInfo.java
  src/main/java/soma/ghostrunner/domain/running/application/support/RunningInfoFilter.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepository.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/global/security/jwt/JwtAuthFilter.java
  src/test/java/soma/ghostrunner/domain/running/api/RunningApiTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
Labels: update

#59 [SGMR-520] 코스 조회 API 응답 필드 추가 & 코스 평균 완주 데이터 집계 API 구현
  src/main/java/soma/ghostrunner/domain/course/api/CourseApi.java
  src/main/java/soma/ghostrunner/domain/course/application/CourseFacade.java
  src/main/java/soma/ghostrunner/domain/course/dto/CourseMapper.java
  src/main/java/soma/ghostrunner/domain/course/dto/CourseWithCoordinatesDto.java
  src/main/java/soma/ghostrunner/domain/course/dto/CourseWithMemberDetailsDto.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseDetailedResponse.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseMapResponse.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseStatisticsResponse.java
  src/main/java/soma/ghostrunner/domain/course/dto/response/CourseSummaryResponse.java
  src/main/java/soma/ghostrunner/domain/course/exception/CourseNotFoundException.java
Labels: update

#62 [SGMR-530] 러닝 리스트 정렬 방식 수정
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningCommandService.java
  src/main/java/soma/ghostrunner/domain/running/dao/CustomRunningRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/domain/Running.java
  src/main/java/soma/ghostrunner/domain/running/domain/RunningDataUrls.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningCommandServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/dao/RunningRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/running/domain/RunningTest.java
Labels: enhancement, fix
