Repository SGMRT/sgmrt-server, pull requests merged in 2025-09, with the labels that each got.

#71 [SGMR-590] 인앱 공지사항 팝업을 위한 기반 시스템 구현
  src/main/java/soma/ghostrunner/clients/aws/upload/GhostRunnerS3Client.java
  src/main/java/soma/ghostrunner/domain/notice/api/NoticeApi.java
  src/main/java/soma/ghostrunner/domain/notice/api/dto/NoticeMapper.java
  src/main/java/soma/ghostrunner/domain/notice/api/dto/request/NoticeCreationRequest.java
  src/main/java/soma/ghostrunner/domain/notice/api/dto/request/NoticeDismissRequest.java
  src/main/java/soma/ghostrunner/domain/notice/api/dto/request/NoticeUpdateRequest.java
  src/main/java/soma/ghostrunner/domain/notice/api/dto/response/NoticeDetailedResponse.java
  src/main/java/soma/ghostrunner/domain/notice/application/NoticeService.java
  src/main/java/soma/ghostrunner/domain/notice/dao/NoticeDismissalRepository.java
  src/main/java/soma/ghostrunner/domain/notice/dao/NoticeRepository.java
  src/main/java/soma/ghostrunner/domain/notice/domain/Notice.java
  src/main/java/soma/ghostrunner/domain/notice/domain/NoticeDismissal.java
  src/main/java/soma/ghostrunner/domain/notice/exceptions/NoticeNotFoundException.java
  src/main/resources/application-dev.yml
  src/test/java/soma/ghostrunner/ApiTestSupport.java
  src/test/java/soma/ghostrunner/domain/notice/api/NoticeApiTest.java
  src/test/java/soma/ghostrunner/domain/notice/api/dto/NoticeMapperTest.java
  src/test/java/soma/ghostrunner/domain/notice/application/NoticeServiceTest.java
  src/test/java/soma/ghostrunner/domain/notice/dao/NoticeDismissalRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/notice/dao/NoticeRepositoryTest.java
  src/test/java/soma/ghostrunner/domain/notice/domain/NoticeDismissalTest.java
  src/test/java/soma/ghostrunner/domain/notice/domain/NoticeTest.java
  src/test/resources/application.yml
Labels: enhancement

#78 [SGMR-645] 러닝 시계열 데이터 필드명 변경 및 데이터 축소
  src/main/java/soma/ghostrunner/domain/course/dao/CustomCourseRepositoryImpl.java
  src/main/java/soma/ghostrunner/domain/running/api/dto/request/TelemetryRequest.java
  src/main/java/soma/ghostrunner/domain/running/application/support/RunningApplicationMapper.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/Checkpoint.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/CoordinateWithTs.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/Coordinates.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/PathSimplifier.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/Telemetry.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/TelemetryProcessor.java
  src/test/java/soma/ghostrunner/domain/running/domain/PathSimplifierTest.java
  src/test/java/soma/ghostrunner/domain/running/domain/support/TelemetryProcessorTest.java
  src/test/resources/data7.jsonl
  src/test/resources/simplified_result_data.jsonl
Labels: refactor

#81 [SGMR-606] EB에서 Nginx의 Request Body Size 반영하도록 수정
  .platform/nginx/conf.d/client_max_body_size.conf
  buildspec.yml
  src/main/java/soma/ghostrunner/domain/DummyApi.java
  src/main/java/soma/ghostrunner/domain/course/domain/Course.java
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/Telemetry.java
Labels: fix

#83 [SGMR-661] 운영 서버용 application.yml 추가
  src/main/java/soma/ghostrunner/domain/notification/application/NotificationService.java
  src/main/resources/application-prod.yml
  src/test/java/soma/ghostrunner/domain/notification/application/NotificationServiceTest.java
Labels: chores

#87 [SGMR-544] 시계열 렌더링 최적화: VW 알고리즘 도입 및 최소 힙과 Lazy Deletion을 이용한 성능 개선 (O(N²)→O(N log N))
  build.gradle
  src/main/java/soma/ghostrunner/domain/running/application/PathSimplificationService.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/CoordinatesWithTs.java
  src/main/java/soma/ghostrunner/domain/running/domain/path/PathSimplifier.java
  src/test/java/soma/ghostrunner/domain/running/domain/PathSimplifierTest.java
  src/test/resources/data7.jsonl
  src/test/resources/simple_data7.jsonl
  src/test/resources/simplified_rdp_data.jsonl
  src/test/resources/simplified_result_data.jsonl
  src/test/resources/simplified_vw_data.jsonl
Labels: refactor

#86 [SGMR-669] 회원 엔티티에 Role 추가, API 보안 강화 및 Swagger CORS 방지 처리
  src/main/java/soma/ghostrunner/domain/auth/application/AuthService.java
  src/main/java/soma/ghostrunner/domain/member/domain/Member.java
  src/main/java/soma/ghostrunner/domain/member/domain/MemberBioInfo.java
  src/main/java/soma/ghostrunner/domain/member/domain/RoleType.java
  src/main/java/soma/ghostrunner/domain/notice/api/NoticeApi.java
  src/main/java/soma/ghostrunner/domain/notification/api/NotificationApi.java
  src/main/java/soma/ghostrunner/global/common/validator/auth/AdminOnly.java
  src/main/java/soma/ghostrunner/global/common/validator/auth/AdminOnlyAspect.java
  src/main/java/soma/ghostrunner/global/config/SecurityConfig.java
  src/main/java/soma/ghostrunner/global/config/SwaggerConfig.java
  src/test/java/soma/ghostrunner/domain/member/domain/MemberTest.java
Labels: update

#90 [SGMR-702] 코스 ID 기반 러닝 목록 조회 API 구현
  src/main/java/soma/ghostrunner/domain/running/api/RunningApi.java
  src/main/java/soma/ghostrunner/domain/running/application/RunningQueryService.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/RunInfo.java
  src/main/java/soma/ghostrunner/domain/running/application/dto/response/RunRecordInfo.java
  src/main/java/soma/ghostrunner/domain/running/application/support/RunningApplicationMapper.java
  src/main/java/soma/ghostrunner/domain/running/infra/persistence/RunningQueryRepository.java
  src/main/java/soma/ghostrunner/domain/running/infra/persistence/RunningRepository.java
  src/test/java/soma/ghostrunner/domain/running/application/PathSimplificationServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/application/RunningQueryServiceTest.java
  src/test/java/soma/ghostrunner/domain/running/infra/RunningRepositoryTest.java
Labels: enhancement
